import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          CommunityForum(),
        ]),
      ),
    );
  }
}

class CommunityForum extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Container(
            width: 360,
            height: 800,
            clipBehavior: Clip.antiAlias,
            decoration: BoxDecoration(color: const Color(0xFFF1EFEB)),
            child: Stack(
              children: [
                Positioned(
                  left: 18,
                  top: 44,
                  child: Text(
                    'Community Forum',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 22,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
                Positioned(
                  left: 262,
                  top: 49,
                  child: Container(
                    width: 24,
                    height: 24,
                    clipBehavior: Clip.antiAlias,
                    decoration: BoxDecoration(),
                    child: Stack(),
                  ),
                ),
                Positioned(
                  left: 318,
                  top: 47,
                  child: Container(
                    width: 24,
                    height: 24,
                    clipBehavior: Clip.antiAlias,
                    decoration: BoxDecoration(),
                    child: Stack(),
                  ),
                ),
                Positioned(
                  left: 18,
                  top: 109,
                  child: Container(
                    width: 24,
                    height: 24,
                    clipBehavior: Clip.antiAlias,
                    decoration: BoxDecoration(),
                    child: Stack(),
                  ),
                ),
                Positioned(
                  left: 57,
                  top: 112,
                  child: SizedBox(
                    width: 84,
                    height: 25,
                    child: Text(
                      'Daily Wins',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 15,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 155,
                  top: 112,
                  child: SizedBox(
                    width: 93,
                    height: 12,
                    child: Text(
                      'Gratitude',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 15,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 237,
                  top: 112,
                  child: SizedBox(
                    width: 88,
                    height: 18,
                    child: Text(
                      'Recovery',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 15,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 19,
                  top: 159,
                  child: SizedBox(
                    width: 122,
                    height: 28,
                    child: Text(
                      'Popular Topics',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 18,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 190,
                  top: 529,
                  child: Container(
                    width: 154,
                    height: 243,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFBABFDA),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 207,
                  top: 550.76,
                  child: SizedBox(
                    width: 83,
                    height: 29.01,
                    child: Text(
                      'Topic 6',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 205,
                  top: 601.54,
                  child: SizedBox(
                    width: 169,
                    height: 84.63,
                    child: Text(
                      'description .......',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 13,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 190,
                  top: 352,
                  child: Container(
                    width: 154,
                    height: 162,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFF2CDB2),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 207,
                  top: 366.51,
                  child: SizedBox(
                    width: 83,
                    height: 19.34,
                    child: Text(
                      'Topic 4',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 205,
                  top: 400.36,
                  child: SizedBox(
                    width: 169,
                    height: 56.42,
                    child: Text(
                      'description .......',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 13,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 18,
                  top: 417,
                  child: Container(
                    width: 154,
                    height: 163,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFD4DABA),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 33,
                  top: 434.23,
                  child: SizedBox(
                    width: 83,
                    height: 22.97,
                    child: Text(
                      'Topic 3',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 18,
                  top: 602,
                  child: Container(
                    width: 154,
                    height: 117,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFD0E6E7),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 33,
                  top: 620,
                  child: SizedBox(
                    width: 83,
                    height: 24,
                    child: Text(
                      'Topic 5',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 190,
                  top: 194,
                  child: Container(
                    width: 154,
                    height: 117,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFBADAD2),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 205,
                  top: 212,
                  child: SizedBox(
                    width: 83,
                    height: 24,
                    child: Text(
                      'Topic 2',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 18,
                  top: 194,
                  child: Container(
                    width: 184,
                    height: 201,
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: -6,
                          child: Container(
                            width: 154,
                            height: 201,
                            decoration: ShapeDecoration(
                              color: const Color(0xFFDABABA),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(20),
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 17,
                          top: 18,
                          child: SizedBox(
                            width: 83,
                            height: 24,
                            child: Text(
                              'Topic 1',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 20,
                                fontFamily: 'Nunito',
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 15,
                          top: 60,
                          child: SizedBox(
                            width: 169,
                            height: 70,
                            child: Text(
                              'description .......',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 13,
                                fontFamily: 'Nunito',
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}